require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'RNFProject' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  target 'RNFProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ReactPushNotifications' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactPushNotifications - Add these lines
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'ReactPushNotificationsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RNFProject-tvOS' do
  # Pods for RNFProject-tvOS

  target 'RNFProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
